=== ZeCarlos88/PRI_A72187_2019/TPC3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project-record (head,team,abstract,deliver) >
<!ELEMENT head (key-name,title,subtitle?,begin-date,end-date,supervisor) >
<!ELEMENT key-name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor 
            href CDATA #REQUIRED >
<!ELEMENT team (member+) >
<!ELEMENT member (#PCDATA) >
<!ATTLIST member
            id ID #REQUIRED
            email CDATA #REQUIRED >
<!ELEMENT abstract (paragraph+) >
<!ELEMENT paragraph (#PCDATA | bold | italic)* >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >
<!ELEMENT deliver (doc+) >
<!ELEMENT doc (#PCDATA) >
<!ATTLIST doc
            href CDATA #REQUIRED>

=== ZeCarlos88/PRI_A72187_2019/TPC8/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "pr.dtd">
<project-record>
    <head>
        <key-name>PRI1920_TPC8</key-name>
        <title>TPC 3</title>
        <begin-date>Outubro 2019</begin-date>
        <end-date>Janeiro 2020</end-date>
        <supervisor href="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </head>
    <team>
        <member id="a72187" email="a72187@alunos.uminho.pt">José Carlos Araújo Lima</member>
    </team>
    <abstract>
    
            <paragraph>Aqui vai feito o tpc8

            </paragraph>
    </abstract>
    <deliver>
        <doc href="pr.dtd">pr.dtd</doc>
        <doc href="pr.xml">pr.xml</doc>
    </deliver>
</project-record>

=== ZeCarlos88/PRI_A72187_2019/TPC3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "pr.dtd">
<project-record>
    <head>
        <key-name>PRI1920_TPC3</key-name>
        <title>TPC 3</title>
        <begin-date>Outubro 2019</begin-date>
        <end-date>Janeiro 2020</end-date>
        <supervisor href="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </head>
    <team>
        <member id="a72187" email="a72187@alunos.uminho.pt">José Carlos Araújo Lima</member>
    </team>
    <abstract>
        <paragraph>
            Este tpc tinha de se fazer duas stylesheet's em formato xsl. Uma delas sendo a stylesheet do project recorde
            e outro para a arqueossítios.
        </paragraph>
        
    </abstract>
    <deliver>
        <doc href="pr.dtd">pr.dtd</doc>
        <doc href="pr.xml">pr.xml</doc>
        <doc href="arq.xsl">arq.txt</doc>
        
    </deliver>
</project-record>

=== ZeCarlos88/PRI_A72187_2019/TPC5/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "pr.dtd">
<project-record>
    <head>
        <key-name>PRI1920_TPC4</key-name>
        <title>TPC 3</title>
        <begin-date>Outubro 2019</begin-date>
        <end-date>Janeiro 2020</end-date>
        <supervisor href="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </head>
    <team>
        <member id="a72187" email="a72187@alunos.uminho.pt">José Carlos Araújo Lima</member>
    </team>
    <abstract>
    
            <paragraph>O Express.js, é uma framework para node que nos permite criar aplicações de forma rápida, fléxivel e eficaz.
                A partir do express, temos acesso a várias bibliotecas e funcionalidades que tornam todo o processo de uma criação de uma aplicação muito minimalista.
                
            </paragraph>
            <paragraph> Os mecanismos fornecidos por esta framework consistem em definir configurações comuns numa aplicação web como a porta a ser usada,
                a localização dos modelos, as renderizações através de ficheiros na pasta "views", etc...
                Apesar de o express parecer complexo, a sua boa documentação e a sua resolução de problemas, permitem aos developers uma rápida maneira de desenvolver aplicações web.
            </paragraph>
            <paragraph>
                Estes projecto, consiste na criação de um Gestor de Alunos ao qual permite listar todos os alunos com a sua respetiva lista de notas.
                Para além de listar, também deve permitir ao utilizador, adicionar alunos, adicionar notas e assim como eliminar alunos e eliminar notas através do seu indicador.
                Para iniciar o servidor, basta correr o comando "npm start" após as dependencias terem sido todas
            </paragraph>
    </abstract>
    <deliver>
        <doc href="pr.dtd">pr.dtd</doc>
        <doc href="pr.xml">pr.xml</doc>
    </deliver>
</project-record>
